POST http://localhost:8081/auth/login
Content-Type: application/json

{

}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    if(response.status === 200) {
        client.global.set("accessToken", response.headers.valueOf("Authorization").slice(7));
    }
%}

####

# Envoi d'un mail simple avec le contenu libre
POST http://localhost:8080/notification/envoi-email
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "destinataire":"nadirsaiah97@gmail.com",
  "objet": "Test envoi mail classique",
  "contenu": "Blablabla, voici un mail classique... "
}

####

# Envoi d'un mail utilisant le template bienvenue.ftl
POST http://localhost:8080/notification/envoi-email-generique
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "destinataire":"nadirsaiah97@gmail.com",
  "objet": "Test envoi mail générique bienvenue"
}

####

# Envoi d'un mail utilisant le template bienvenue.ftl
POST http://localhost:8080/notification/envoi-email-pieceJointe
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "destinataire":"nadirsaiah97@gmail.com",
  "objet": "Test envoi mail générique bienvenue"
}