POST http://localhost:8081/auth/connexion
Content-Type: application/json

{
  "email": "root@root.com",
  "motDePasse": "root"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    if(response.status === 200) {
        client.global.set("accessToken", response.headers.valueOf("Authorization").slice(7));
    }
%}

####

# Envoi d'un mail de bienvenu utilisant le template bienvenue.ftl
POST http://localhost:8080/notification/email-bienvenu
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "destinataire":"nadirsaiah97@gmail.com",
  "objet": "Test envoi mail bienvenue"
}

####

# Envoi d'un mail de confirmation de commande utilisant le template commande.ftl
POST http://localhost:8080/notification/email-confirm-commande
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "destinataire":"nadirsaiah97@gmail.com",
  "objet": "Test envoi mail de confirmation de commande",
  "cheminPieceJointe": "/logo/Fond_Noir_V2.png"
}